SECRET_KEY = b'makeyourownkey'

#Else using MySQL.  See freemysqlhosting.net for free mySQL.
DB_USERNAME = "sql_username"
DB_PASSWORD = "sql_password"
DB_HOST     = "sqlhost.sql.com"
DB_DATABASE = "db_name"

SQLALCHEMY_DATABASE_URI = "mysql+mysqlconnector://{}:{}@{}/{}"\
.format(DB_USERNAME, DB_PASSWORD, DB_HOST, DB_DATABASE)

#SQLALCHEMY_TRACK_MODIFICATIONS = True
#SQLALCHEMY_ECHO = True

#PYTHONANYWHERE CONFIG:
#SQLALCHEMY_POOL_RECYCLE = 280   # See http://help.pythonanywhere.com/pages/UsingSQLAlchemywithMySQL/

# MAIL SETTINGS
#POSTALE SETTINGS
MAIL_SERVER = "mailserver.com"
MAIL_USERNAME = "a@b.com"
MAIL_SENDER = "Sender Name <a@b.com"
MAIL_PASSWORD = "mailpassword"
MAIL_PORT = 587
MAIL_USE_SSL = False
MAIL_USE_TLS = True
MAIL_DEBUG = 0

# SALT FOR EMAIL CONFIRMATION
SALT = b'setyourown'

# FOR EMAIL CONFIRMATION - FUTURE USE
# ROOT_URL = "http://127.0.0.1:5000"

# PATH FOR FILE UPLOADS - FUTURE USE
#UPLOAD_FOLDER = '/uploads/'

# MAX FILE UPLOAD SIZE - FUTURE USE
#MAX_CONTENT_LENGTH = 2 * 1024 * 1024    # 2MB.  This might have some side effects but I can't find a better server side option.
                                        # - JG, 4/13/20

# USED FOR GOOGLE ANALYTICS.  IF NOT PRODUCTION, DO NOT INCLUDE THE TRACKING SCRIPT. - FUTURE USE
#IS_PRODUCTION = False

# RECAPTCHA KEYS - DIFFERENT KEYS FOR DEV AND PROD
#RECAPTCHA_PUBLIC_KEY_DEV = "6LfWzPUUAAAAAFieJ1lCEZZZZP-ANgxx_SUjLGL"
#RECAPTCHA_PRIVATE_KEY_DEV = "6LfWzPUUAAAAADeQs4fZjgZZZDuObg-ZjX7M7Puc"
#TESTING = True
#RECAPTCHA_PUBLIC_KEY_PROD = "6LeBzPUUAAAAAF0ZZZl8sWdi0SJ_CZ42nZ0Vn"
#RECAPTCHA_PRIVATE_KEY_PROD = "6LeBzPUUAAAAAD5urAZZZbdFDkHdx_-q79jZY_"