"""Added dogs table

Revision ID: 240c97881461
Revises: 826b0a54b8e9
Create Date: 2020-11-23 10:56:12.848277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240c97881461'
down_revision = '826b0a54b8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    # ### end Alembic commands ###
