"""Temporarily remove verification token field.

Revision ID: 3bfa9c4ea4e8
Revises: d002ff91c0b8
Create Date: 2020-11-29 22:27:02.801998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bfa9c4ea4e8'
down_revision = 'd002ff91c0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_token', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
