"""Temp removal of password field.

Revision ID: 95702c88e365
Revises: d79607eba4c5
Create Date: 2020-11-30 20:16:04.906874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95702c88e365'
down_revision = 'd79607eba4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###
